apiVersion: v1
kind: Pod
metadata:
labels:
  component: ci
spec:
  containers:
  - name: travela-backend-agent
    image: eu.gcr.io/jenkins-apprenticeship/jenkins-travela-backend
    resources:
      requests:
        cpu: "2000m"
        memory: "2Gi"
      limits:
        cpu: "2000m"
        memory: "2Gi"
    command:
    - cat
    tty: true
    env:
      - name: DOCKER_HOST
        value: tcp://localhost:2375
  - name: travela-backend-database
    image: postgres:9.6-alpine
    env:
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_DB
        value: travela
      - name: POSTGRES_PASSWORD
        value: postgres
  - name: dind
    image: docker:18.05-dind
    securityContext:
      privileged: true
    volumeMounts:
      - name: dind-storage
        mountPath: /var/lib/docker
  volumes:
  - name: dind-storage
    emptyDir: {}
